name: ot2
services:
  ot2_module:
    container_name: ot2
    image: ot2
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - ot2:latest
        - ot2:dev
    command: python ot2_module/src/ot2_rest_node.py --port 2000 --ot2_ip ${OT2_IP}
    privileged: true
    env_file: .env
    volumes:
      - ./src:/home/app/ot2_module/src
      - ./tests:/home/app/ot2_module/tests
    ports:
      - 2000:2000
