equipment:
  - name: corning_96_wellplate_360ul_flat
    location: "2"
    alias: source
  - name: corning_96_wellplate_360ul_flat
    location: "3"
    alias: dest
  - name: opentrons_96_tiprack_1000ul
    location: "8"
  - name: p1000_single_gen2
    mount: right
commands:
  - name: example command
    command: transfer
    source: source:A1
    destination: dest:A1
    volume: 100
  - name: other command
    command: transfer
    source: source:A2
    destination: dest:A2
    volume: 100
metadata:
  protocolName: Example Name
  author: Kyle khippe@anl.gov
  description: basic_config.yml
  apiLevel: "2.12"
